### ISSUE TITLE
Finish Work on Ranker Object

### ISSUE THREAD

**Issue by shreystechtips** [NRG948/NRGScoutingApp2019DeepSpace#4]
This object will be responsible for handling all ranking requests and will have methods which return some type of collection for all the different ranking types in the match

**Comment by shreystechtips** [comment]
Finished Calculating Average Hatch and Cargo TImes

**Comment by shreystechtips** [comment]
Finished Lvl1,2,3 drop average time

**Comment by shreystechtips** [comment]
Started work on climb ranker, but needs a logic update.

**Comment by dowhep** [comment]
hatch and Cargo ranker doesn't work on rankers

**Comment by shreystechtips** [comment]
@dowhep, can you please expand on what is not working so I can look into it

**Comment by MarceloShen** [comment]
I mean Android

**Comment by MarceloShen** [comment]
it failed to show matches although there is catch and drop events
